# Generated by Django 4.0.4 on 2022-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
